name: thesis_env
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py312h4c3975b_0
  - arrow=1.3.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - attrs=25.3.0=pyh71513ae_0
  - babel=2.17.0=pyhd8ed1ab_0
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - brotli-python=1.1.0=py312h1289d80_4
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h3394656_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - comm=0.2.3=pyhe01879c_0
  - cudatoolkit=11.8.0=h4ba93d1_13
  - debugpy=1.8.16=py312h8285ef7_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - faiss=1.9.0=py312cuda118h19f20af_0_cuda
  - faiss-gpu=1.9.0=h418687c_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.14.1=ha770c72_0
  - graphite2=1.3.14=hecca717_2
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=11.5.1=h15599e2_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.30.1=pyh82676e8_0
  - ipython=9.4.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py312h7900ff3_2
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.9=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - kernel-headers_linux-64=5.14.0=he073ed8_2
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.44=h1423503_1
  - libblas=3.9.0=37_h4a7cf45_openblas
  - libcblas=3.9.0=37_h0358290_openblas
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libexpat=2.7.1=hecca717_0
  - libfaiss=1.9.0=cuda118hf323835_0_cuda
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.1.0=h767d61c_4
  - libgcc-ng=15.1.0=h69a702a_4
  - libgfortran=15.1.0=h69a702a_5
  - libgfortran5=15.1.0=hcea5267_5
  - libglib=2.86.0=h1fed272_0
  - libgomp=15.1.0=h767d61c_4
  - libiconv=1.18=h3b78370_2
  - liblapack=3.9.0=37_h47877c9_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_2
  - libpng=1.6.50=h421ea60_1
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.50.4=h0c1763c_0
  - libstdcxx=15.1.0=h8f9b012_4
  - libstdcxx-ng=15.1.0=h4852527_4
  - libuuid=2.38.1=h0b41bf4_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mistune=3.1.4=pyhcf101f3_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - notebook=7.4.7=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numpy=1.26.4=py312heda63a1_0
  - openssl=3.5.4=h26f9b46_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_1
  - pcre2=10.46=h1321c63_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - platformdirs=4.3.8=pyhe01879c_0
  - prometheus_client=0.23.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=7.0.0=py312h66e93f0_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.12.11=h9e4cc4f_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python_abi=3.12=8_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - pyzmq=27.0.1=py312h6748674_0
  - readline=8.2=h8c095d6_2
  - referencing=0.36.2=pyh29332c3_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - send2trash=1.8.3=pyh0d859eb_1
  - six=1.17.0=pyhe01879c_1
  - sniffio=1.3.1=pyhd8ed1ab_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - sysroot_linux-64=2.34=h087de78_2
  - tectonic=0.15.0=h69b855b_3
  - terminado=0.18.1=pyh0d859eb_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_hd72426e_102
  - tomli=2.2.1=pyhe01879c_2
  - tornado=6.5.1=py312h66e93f0_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - types-python-dateutil=2.9.0.20250822=pyhd8ed1ab_0
  - typing-extensions=4.14.1=h4440ef1_0
  - typing_extensions=4.14.1=pyhe01879c_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - yaml=0.2.5=h280c20c_3
  - zeromq=4.3.5=h3b0a872_7
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.25.0=py312h5253ce2_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - accelerate==1.10.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.10.0
      - astor==0.8.1
      - beautifulsoup4==4.13.4
      - bitsandbytes==0.47.0
      - blake3==1.0.5
      - cachetools==6.1.0
      - cbor==1.0.0
      - cbor2==5.6.5
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - click==8.2.1
      - cloudpickle==3.1.1
      - compressed-tensors==0.10.2
      - contourpy==1.3.3
      - cupy-cuda12x==13.5.1
      - cycler==0.12.1
      - datasets==4.0.0
      - depyf==0.19.0
      - dill==0.3.8
      - diskcache==5.6.3
      - distro==1.9.0
      - dnspython==2.7.0
      - einops==0.8.1
      - email-validator==2.2.0
      - fastapi==0.116.1
      - fastapi-cli==0.0.8
      - fastapi-cloud-cli==0.1.5
      - fastrlock==0.8.3
      - filelock==3.18.0
      - fire==0.7.0
      - flagembedding==1.3.5
      - fonttools==4.60.0
      - frozenlist==1.7.0
      - fsspec==2025.3.0
      - gguf==0.17.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - hf-xet==1.1.7
      - httptools==0.6.4
      - huggingface-hub==0.34.3
      - ijson==3.4.0
      - inscriptis==2.6.0
      - interegular==0.3.3
      - ir-datasets==0.5.11
      - jiter==0.10.0
      - joblib==1.5.1
      - jsonschema==4.25.0
      - jsonschema-specifications==2025.4.1
      - kiwisolver==1.4.9
      - lark==1.2.2
      - llguidance==0.7.30
      - llvmlite==0.44.0
      - lm-format-enforcer==0.10.12
      - lxml==6.0.0
      - lz4==4.4.4
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.6
      - mdurl==0.1.2
      - mistral-common==1.8.3
      - mpmath==1.3.0
      - msgpack==1.1.1
      - msgspec==0.19.0
      - multidict==6.6.3
      - multiprocess==0.70.16
      - networkx==3.5
      - ninja==1.11.1.4
      - numba==0.61.2
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - openai==1.90.0
      - opencv-python-headless==4.12.0.88
      - outlines-core==0.2.10
      - pandas==2.3.1
      - pandoc==2.4
      - partial-json-parser==0.2.1.1.post6
      - peft==0.17.0
      - pillow==11.3.0
      - plumbum==1.9.0
      - ply==3.11
      - prometheus-client==0.22.1
      - prometheus-fastapi-instrumentator==7.1.0
      - propcache==0.3.2
      - protobuf==6.31.1
      - py-cpuinfo==9.0.0
      - pyarrow==21.0.0
      - pybase64==1.4.2
      - pycountry==24.6.1
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydantic-extra-types==2.10.5
      - pyparsing==3.2.5
      - python-dotenv==1.1.1
      - python-json-logger==3.3.0
      - python-multipart==0.0.20
      - pyyaml==6.0.2
      - ray==2.48.0
      - regex==2025.7.34
      - requests==2.32.4
      - rich==14.1.0
      - rich-toolkit==0.14.9
      - rignore==0.6.4
      - rpds-py==0.27.0
      - safetensors==0.6.1
      - scikit-learn==1.7.1
      - scipy==1.16.1
      - seaborn==0.13.2
      - sentence-transformers==5.1.0
      - sentencepiece==0.2.0
      - sentry-sdk==2.34.1
      - setuptools==79.0.1
      - shellingham==1.5.4
      - smmap==5.0.2
      - soundfile==0.13.1
      - soupsieve==2.7
      - soxr==0.5.0.post1
      - starlette==0.47.2
      - sympy==1.14.0
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - tiktoken==0.10.0
      - tokenizers==0.21.4
      - torch==2.7.1+cu126
      - torchaudio==2.7.1+cu126
      - torchvision==0.22.1+cu126
      - tqdm==4.67.1
      - transformers==4.55.0
      - trec-car-tools==2.6
      - triton==3.3.1
      - typer==0.16.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - unlzw3==0.2.3
      - uvicorn==0.35.0
      - uvloop==0.21.0
      - vllm==0.10.0
      - wandb==0.21.1
      - warc3-wet==0.2.5
      - warc3-wet-clueweb09==0.2.5
      - watchfiles==1.1.0
      - websockets==15.0.1
      - xformers==0.0.31
      - xgrammar==0.1.21
      - xxhash==3.5.0
      - yarl==1.20.1
      - zlib-state==0.1.9
